name: Dana Silver

markdown: redcarpet
redcarpet:
    extensions: ['fenced_code_blocks', 'autolink', 'tables', 'no_intra_emphasis']

pygments: true
pygments_options: ['lineanchors']

exclude: ['less',
          '.gitignore',
          '*.sublime-*',
          'README.md',
          'js',
          'build.py',
          'build_gh.sh',
          'snapchat-db-stats',
          'Gemfile']

permalink: pretty

splash_imgs: ['/static/imgs/splash/tetons_short.jpg', '/static/imgs/splash/bikeburl_short.jpg']